Added Chef Server status check

diff --git a/CEPH_UP b/CEPH_UP
--- a/CEPH_UP
+++ b/CEPH_UP
@@ -247,7 +247,10 @@ sudo $REPO_ROOT/bootstrap/common/cepheus_bootstrap_init.sh $REPO_ROOT $BUILD_LOC
 
 echo "====> Calling bootstrap_chef_server.sh..."
 TMP_REPO_ROOT=$REPO_ROOT
+# Just a safe check because this part can fail and be fine.
+set +e
 source $REPO_ROOT/bootstrap/common/bootstrap_chef_server.sh $REPO_ROOT
+set -e
 
 echo "====> Calling cepheus_build_update.sh..."
 source $TMP_REPO_ROOT/bootstrap/common/cepheus_build_update.sh
