Added option to CEPH_UP

diff --git a/data/templates/bootstrap/common/cepheus_build_update.sh.j2 b/data/templates/bootstrap/common/cepheus_build_update.sh.j2
--- a/data/templates/bootstrap/common/cepheus_build_update.sh.j2
+++ b/data/templates/bootstrap/common/cepheus_build_update.sh.j2
@@ -93,18 +93,23 @@ cp -rp $WORK_DIR/ceph-chef-private-staging/* $WORK_DIR/ceph-chef-public-staging/
 cp -rp $WORK_DIR/ceph-chef-public-staging/* $WORK_DIR/cepheus-public-staging/
 cp -rp $WORK_DIR/cepheus-data-staging/* $WORK_DIR/cepheus-public-staging/
 
+# Create template files for staging before moving...
+cd $WORK_DIR/cepheus-public-staging
+./CEPH_UP -z $WORK_DIR/cepheus-public-staging
+
 echo "====> Clean staging process directories..."
 # Clean up staging process directories if they exist
 # NOTE: Important - Do this BEFORE moving data into directories on bootstrap since *all* is used!!
 
-set +e
-# Only if Chef has been installed which means ansible is loaded and host files exist
-if [[ -d "/opt/opscode/" ]]; then
-    # Nodes may not exist during initial build so it's ok to fail...
-    ansible all -m shell -a "sudo rm -rf $REPO_ROOT"
-    ansible all -m shell -a "sudo rm -rf $REPO_ROOT_FILES"
-fi
-set -e
+# NOTE: Come back to this later because attempting to run this section on new system fails badly!
+# set +e
+# # Only if Chef has been installed which means ansible is loaded and host files exist
+# if [[ -d "/opt/opscode/" ]]; then
+#     # Nodes may not exist during initial build so it's ok to fail...
+#     ansible all -m shell -a "sudo rm -rf $REPO_ROOT"
+#     ansible all -m shell -a "sudo rm -rf $REPO_ROOT_FILES"
+# fi
+# set -e
 
 echo "====> Building update..."
 # Build new ceph-host environment and replace existing version
@@ -203,16 +208,16 @@ logger -t CepheusBackup "Cepheus Chef Server updated to latest packages - $VERSI
 # Hack around gem issue - one of Chef's bad things...
 # NB: Fix in future - Should only run these ansible runs *IF* nodes exists but for now it's ok if they fail on intial run...
 set +e
-{% for item in ceph_chef.gems %}
-ansible all -m copy -a "src=$REPO_ROOT_FILES/gems/{{ item.name }}-{{ item.version }}.gem dest=/tmp/{{ item.name }}-{{ item.version }}.gem owner=$OWNER"
-{% endfor %}
+# {% for item in ceph_chef.gems %}
+# ansible all -m copy -a "src=$REPO_ROOT_FILES/gems/{{ item.name }}-{{ item.version }}.gem dest=/tmp/{{ item.name }}-{{ item.version }}.gem owner=$OWNER"
+# {% endfor %}
 
 # Backup ALL important configs, keys etc
 # I have seen this sometimes hang - maybe due to doing a number of crush map gets which means it needs to be
 # optimized to only get configs for each of the node groups since the configs are the same for all in that group and
 # then maybe store the backup on the boostrap as well as the primary node in the given group. Until then, it's OK to ctrl-c out of it.
 
-ansible {{ inventory.ceph.backup.primary.mon }},{{ inventory.ceph.backup.primary.osd }},{{ inventory.ceph.backup.primary.rgw }} -m shell -a "sudo /etc/ceph/scripts/ceph_backup_files.sh $VERSION $DATE"
+# ansible {{ inventory.ceph.backup.primary.mon }},{{ inventory.ceph.backup.primary.osd }},{{ inventory.ceph.backup.primary.rgw }} -m shell -a "sudo /etc/ceph/scripts/ceph_backup_files.sh $VERSION $DATE"
 set -e
 ##################
 
